import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navber from "@/component/UI/navber";
import Footer from "@/component/UI/footer";
import { Providers } from "@/lib/Providers";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="container mx-auto max-w-8xl  px-6 flex-grow">
        <Providers>
        <div className="flex flex-col">
        <div className="flex-grow min-h-screen">
        <Navber />
       <div>
       {children}
       </div>
        </div>
       <div className="flex-shrink-0">
       <Footer />
       </div>
        </div>
        </Providers>
        </main>
      </body>
    </html>
  );
}
